import Head from "next/head";
import { Inter } from "next/font/google";
import Board from "../components/Board";
import StartModal from "../components/Modal/StartModal";
import RulesModal from "../components/Modal/RulesModal";
import PauseModal from "../components/Modal/PauseModal";
import { authModalState } from "../atoms/modalAtom";
import { useRecoilState } from "recoil";
import Game from "../components/Game/Game";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [modalState, setModalState] = useRecoilState(authModalState);
  console.log(modalState, "state");
  const updateState = () => {
    setModalState((prev) => ({ ...prev, open: false }));
    console.log(modalState, "po");
  };
  return (
    <>
      <Head>
        <title>Frontend Mentor | Connect Four game</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/images/favicon-32x32.png"
        />
      </Head>
      <main className="">
        {/* <button onClick={updateState}>aaaaaaaa</button> */}
        {/* {modalState.open && (
          <>
            {modalState.view === "start" && <StartModal />}
            {modalState.view === "pause" && <PauseModal />}
            {modalState.view === "rules" && <RulesModal />}
          </>
        )} */}
        {/* <Board /> */}
        {/* <StartModal /> */}
        {/* <RulesModal /> */}

        {/* <Board /> */}
        <Game />
      </main>
    </>
  );
}
